const projectsData = [
    {
        title: 'EleCommerce',
        category: 'NODEJS / REACTJS',
        text: 'Aplicación de comercio electrónico con carrito de compras, pasarela de pagos y gestión de productos.',
        image: 'https://res.cloudinary.com/dnx4de9yv/image/upload/v1770080444/Portafolio/s8unjpx9oowtiv47dn0y.jpg',
        link: 'https://ele-commerce.vercel.app',
    },
    {
        title: 'Crisol de Ideas',
        category: 'NODEJS / REACTJS',
        text: 'Blog personal con sistema de autenticación, gestión de publicaciones y comentarios.',
        image: 'https://res.cloudinary.com/dnx4de9yv/image/upload/v1770081631/Portafolio/wtrzoc6n2tkkfnnxdgai.jpg',
        link: 'https://blog-app-web-crisol.vercel.app',
    },
    {
        title: 'Livicom',
        category: 'SHOPIFY',
        text: 'livicom.example.com',
        image: 'https://picsum.photos/600/400?random=11',
        link: 'https://livicom.com',
    },
    {
        title: 'Istanbul Cruise Transfer',
        category: 'TOUR',
        text: 'cruise.example.com',
        image: 'https://picsum.photos/600/400?random=10',
        link: 'https://istanbulcruisetransfer.com',
    },
    {
        title: 'Tour Control Dashboard',
        category: 'DASHBOARD',
        text: 'dashboard.example.com',
        image: 'https://picsum.photos/600/400?random=9',
        link: 'https://tourcontrol.com',
    },
    {
        title: 'Tour Control Dashboard',
        category: 'DASHBOARD',
        text: 'dashboard.example.com',
        image: 'https://picsum.photos/600/400?random=9',
        link: 'https://tourcontrol.com',
    },
    {
        title: 'Tour Control Dashboard',
        category: 'DASHBOARD',
        text: 'dashboard.example.com',
        image: 'https://picsum.photos/600/400?random=9',
        link: 'https://tourcontrol.com',
    },
    {
        title: 'Tour Control Dashboard',
        category: 'DASHBOARD',
        text: 'dashboard.example.com',
        image: 'https://picsum.photos/600/400?random=9',
        link: 'https://tourcontrol.com',
    },
    {
        title: 'Tour Control Dashboard',
        category: 'DASHBOARD',
        text: 'dashboard.example.com',
        image: 'https://picsum.photos/600/400?random=9',
        link: 'https://tourcontrol.com',
    },
    {
        title: 'Tour Control Dashboard',
        category: 'DASHBOARD',
        text: 'dashboard.example.com',
        image: 'https://picsum.photos/600/400?random=9',
        link: 'https://tourcontrol.com',
    },
    {
        title: 'Tour Control Dashboard',
        category: 'DASHBOARD',
        text: 'dashboard.example.com',
        image: 'https://picsum.photos/600/400?random=9',
        link: 'https://tourcontrol.com',
    },
]

export default projectsData